on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4

      - name: Run tests and produce coverage reports
        run: make

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
